global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'mailcatcher:1025'
  smtp_from: 'curso@loki.es'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

route:
  receiver: 'myapp'

receivers:
  - name: 'myapp'
    email_configs:
    - to: 'receptor@loki.es'